version: "1.0"

services:
  # mydb:
  #    container_name: mydb
  #    image: postgres:12
  #    environment:
  #       POSTGRES_USER: postgres
  #       POSTGRES_PASSWORD: 123456
  #       POSTGRES_DB: mydb
  #    ports:
  #      - '5432:5432'
  #    volumes:
  #      - pgdata:/var/lib/postgresql/data
  app:
    container_name: app
    image: myapp:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile
      args:
         DATABASE_URL: postgres://postgres:123456@db:5432/mydb
         APP_ADDRESS : 0.0.0.0
         APP_PORT : 8081
    # depends_on:
    #   - mydb
    ports:
      - '8081:8081'
    hostname: loacalapp
# volumes:
#   pgdata: {}